[versions]
# Plugins
shadow = "8.1.7"

# Tooling
kotlin-coroutines = "1.9.0-RC"
guava = "32.1.2-jre"
slf4j = "2.0.9"
caffeine = "3.1.8"

[plugins]
shadow = { id = "io.github.goooler.shadow", version.ref = "shadow" }

[libraries]
# Tooling
kotlin-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
caffeine = { group = "com.github.ben-manes.caffeine", name = "caffeine", version.ref = "caffeine" }
